### ISSUE TITLE
Non-existent file supplied as LLVM_CONFIG= causes an error not saying what file is missing

### ISSUE THREAD

**Issue by yurivict** [revng/llvmcpy#18]
This is a small matter, but please change this to some readable error message:

```
>>> from llvmcpy import llvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/llvmcpy/llvm.py", line 678, in <module>
    version = run_llvm_config(["--version"])
  File "/usr/local/lib/python2.7/site-packages/llvmcpy/llvm.py", line 339, in run_llvm_config
    return subprocess.check_output([llvm_config] + args).decode("utf-8").strip()
  File "/usr/local/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/lib/python2.7/subprocess.py", line 1025, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by aleclearmind** [comment]
Can you please provide a patch for this?

**Comment by aleclearmind** [comment]
Can you please see if e50f550cf50670fbd86f74aee285d23c65ee3b0a (branch `feature/better-program-search`) fixes the issue?

**Comment by aleclearmind** [comment]
I assume it does, feel free to reopen this issue in case of problems.
